### ISSUE TITLE
VS Code Vim Settings (settings.json)

### ISSUE THREAD

**Issue by wavitygyu** [itsnamgyu/setup#1]
{
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
  "vim.insertModeKeyBindings": [
    {
      "before": ["f", "j"],
      "after": ["<Esc>"]
    },
    {
      "before": ["j", "f"],
      "after": ["<Esc>"]
    },
    {
      "before": ["F", "j"],
      "after": ["<Esc>"]
    },
    {
      "before": ["J", "f"],
      "after": ["<Esc>"]
    },
  ],
}

**Comment by itsnamgyu** [comment]
Added!
